version: "3.7"
services:
  application:
    container_name: python-musical-bot
    build: .
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /Users/seungmin/study/project/musical-twitterbot:/root/musical-twitterbot
    restart: always