version: "3.7"
services:
  application:
    container_name: python-musical-bot
    build: .
    restart: always
  mysql: 
    image: mysql:5.7 
    volumes: 
     - ./db/mysql/data:/var/lib/mysql
     - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports: 
     - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234