version: "3.7"
services:
  application:
    container_name: python-musical-bot
    build: .
    restart: always
    depends_on: 
     - mysql
    shm_size: '3gb'
  mysql: 
    command: --explicit_defaults_for_timestamp=1
    image: mysql:5.7.28 
    volumes: 
     - ./db_data:/var/lib/mysql
     - ./db/mysql:/docker-entrypoint-initdb.d
    ports: 
     - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER} 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes: 
  db_data: 
